### ISSUE TITLE
Ref for PreparedStatement resource does not follow documentation

### ISSUE THREAD

**Issue by mjalkio** [aws-cloudformation/aws-cloudformation-resource-providers-athena#37]
The `AWS::Athena::PreparedStatement` resource is [documented](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-preparedstatement.html#aws-resource-athena-preparedstatement-return-values) with the following description:
> When you pass the logical ID of this resource to the intrinsic `Ref` function, `Ref` returns the name of the prepared statement.

However when I define:
```
  ExampleStatement:
    Type: AWS::Athena::PreparedStatement
    Properties:
      Description: Example for Slack.
      QueryStatement: SELECT 1
      StatementName: Test
      WorkGroup: primary
```

And then use `!Ref ExampleStatement` it returns `Test|primary`. I believe that this is a bug. I believe the behavior in the documentation is preferred, my example should return `Test`. However, I haven't gone very deep with prepared statements, so it's possible that `Test|primary` is better for a reason I'm unaware of.
